<?php

namespace Database\Seeders;

use App\Models\Driver;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class DriverSeeder extends Seeder
{
    /**
     * Run the database seeder.
     */
    public function run(): void
    {
        $drivers = [
            [
                'name' => 'Carlos Roberto da Silva',
                'birth_date' => '1985-03-15',
                'registration_number' => '123456',
                'cpf' => '04824716006',
                'rg' => '2130204437',
                'zip_code' => '96015190',
                'street' => 'Rua Major Cícero de Góes Monteiro',
                'number' => '1056',
                'city' => 'Pelotas',
                'state' => 'RS',
                'email' => 'carlos.roberto@gmail.com',
                'phone' => '53984492078',
                'cnh_category' => 'D',
                'cnh_number' => '1648245',
                'cnh_expiry_date' => '2025-08-25',
            ],
            [
                'name' => 'Amanda Siqueira Santos',
                'birth_date' => '1990-07-22',
                'registration_number' => '234567',
                'cpf' => '12345678901',
                'rg' => '3456789012',
                'zip_code' => '01310100',
                'street' => 'Avenida Paulista',
                'number' => '1578',
                'city' => 'São Paulo',
                'state' => 'SP',
                'email' => 'amanda.siqueira@gmail.com',
                'phone' => '11987654321',
                'cnh_category' => 'D',
                'cnh_number' => '2759346',
                'cnh_expiry_date' => '2026-01-15',
            ],
            [
                'name' => 'João Pedro Oliveira',
                'birth_date' => '1982-11-08',
                'registration_number' => '345678',
                'cpf' => '98765432109',
                'rg' => '5678901234',
                'zip_code' => '20040020',
                'street' => 'Avenida Rio Branco',
                'number' => '156',
                'city' => 'Rio de Janeiro',
                'state' => 'RJ',
                'email' => 'joao.pedro@gmail.com',
                'phone' => '21976543210',
                'cnh_category' => 'E',
                'cnh_number' => '3864527',
                'cnh_expiry_date' => '2025-12-10',
            ],
            [
                'name' => 'Maria Fernanda Costa',
                'birth_date' => '1988-05-30',
                'registration_number' => '456789',
                'cpf' => '11122233344',
                'rg' => '7890123456',
                'zip_code' => '30130010',
                'street' => 'Rua da Bahia',
                'number' => '789',
                'city' => 'Belo Horizonte',
                'state' => 'MG',
                'email' => 'maria.fernanda@gmail.com',
                'phone' => '31965432109',
                'cnh_category' => 'D',
                'cnh_number' => '4975618',
                'cnh_expiry_date' => '2024-11-20', // CNH vencida
            ],
            [
                'name' => 'Ricardo Almeida Souza',
                'birth_date' => '1975-09-12',
                'registration_number' => '567890',
                'cpf' => '55566677788',
                'rg' => '9012345678',
                'zip_code' => '40070110',
                'street' => 'Avenida Sete de Setembro',
                'number' => '234',
                'city' => 'Salvador',
                'state' => 'BA',
                'email' => 'ricardo.almeida@gmail.com',
                'phone' => '71954321098',
                'cnh_category' => 'D',
                'cnh_number' => '5086739',
                'cnh_expiry_date' => '2025-06-18',
            ],
            [
                'name' => 'Ana Paula Ferreira',
                'birth_date' => '1993-01-25',
                'registration_number' => '678901',
                'cpf' => '99988877766',
                'rg' => '1234567890',
                'zip_code' => '60160230',
                'street' => 'Rua Monsenhor Tabosa',
                'number' => '567',
                'city' => 'Fortaleza',
                'state' => 'CE',
                'email' => 'ana.paula@gmail.com',
                'phone' => '85943210987',
                'cnh_category' => 'C',
                'cnh_number' => '6197840',
                'cnh_expiry_date' => '2026-03-22',
            ],
            [
                'name' => 'Luiz Carlos Mendes',
                'birth_date' => '1980-12-03',
                'registration_number' => '789012',
                'cpf' => '33344455566',
                'rg' => '2345678901',
                'zip_code' => '80010000',
                'street' => 'Rua XV de Novembro',
                'number' => '890',
                'city' => 'Curitiba',
                'state' => 'PR',
                'email' => 'luiz.carlos@gmail.com',
                'phone' => '41932109876',
                'cnh_category' => 'D',
                'cnh_number' => '7208951',
                'cnh_expiry_date' => '2025-09-14',
            ],
            [
                'name' => 'Juliana Rodrigues Lima',
                'birth_date' => '1987-04-18',
                'registration_number' => '890123',
                'cpf' => '77788899900',
                'rg' => '3456789012',
                'zip_code' => '88010400',
                'street' => 'Rua Felipe Schmidt',
                'number' => '123',
                'city' => 'Florianópolis',
                'state' => 'SC',
                'email' => 'juliana.rodrigues@gmail.com',
                'phone' => '48921098765',
                'cnh_category' => 'D',
                'cnh_number' => '8310062',
                'cnh_expiry_date' => '2025-07-30',
            ],
            [
                'name' => 'Roberto Silva Pereira',
                'birth_date' => '1979-08-07',
                'registration_number' => '901234',
                'cpf' => '11100099988',
                'rg' => '4567890123',
                'zip_code' => '70040010',
                'street' => 'Esplanada dos Ministérios',
                'number' => '456',
                'city' => 'Brasília',
                'state' => 'DF',
                'email' => 'roberto.silva@gmail.com',
                'phone' => '61910987654',
                'cnh_category' => 'E',
                'cnh_number' => '9421173',
                'cnh_expiry_date' => '2026-02-11',
            ],
            [
                'name' => 'Patrícia Gomes Barbosa',
                'birth_date' => '1991-06-14',
                'registration_number' => '012345',
                'cpf' => '22233344455',
                'rg' => '5678901234',
                'zip_code' => '69020160',
                'street' => 'Avenida Eduardo Ribeiro',
                'number' => '789',
                'city' => 'Manaus',
                'state' => 'AM',
                'email' => 'patricia.gomes@gmail.com',
                'phone' => '92909876543',
                'cnh_category' => 'D',
                'cnh_number' => '0532284',
                'cnh_expiry_date' => '2025-10-05',
            ],
        ];

        foreach ($drivers as $driverData) {
            Driver::create($driverData);
        }
    }
}
